name: Test
version: 0.0.1
schema: v1
models:
  - name: "Test Sonnet"
    provider: openrouter
    model: anthropic/claude-sonnet-4.5
    apiBase: https://openrouter.ai/api/v1
    apiKey: "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"