name: OpenRouter Setup
version: 0.0.1
schema: v1

models:
  - name: "[$$] • 200K • [TXT] • Claude Sonnet 4.5"
    provider: openrouter
    model: anthropic/claude-sonnet-4.5
    apiBase: https://openrouter.ai/api/v1
    apiKey: "sk-or-v1-YOUR_ACTUAL_KEY_HERE"
    capabilities:
      tools: true

  - name: "[FREE] • 262K • [TXT] • Qwen3 Coder"
    provider: openrouter
    model: qwen/qwen3-coder-free
    apiBase: https://openrouter.ai/api/v1
    apiKey: "sk-or-v1-YOUR_ACTUAL_KEY_HERE"

  - name: "[$] • 128K • [TXT] • GLM 4 32B"
    provider: openrouter
    model: z-ai/glm-4-32b
    apiBase: https://openrouter.ai/api/v1
    apiKey: "sk-or-v1-YOUR_ACTUAL_KEY_HERE"
    capabilities:
      tools: true